# Identificação do projeto
sonar.projectKey=projetoMSS
sonar.organization=diogo Gianezi de Melo
sonar.projectName=projetoMSS
sonar.projectVersion=1.0

# URL do SonarCloud
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.python.coverage.reportPaths=coverage.xml

# Linguagem
sonar.language=py

sonar.newCode.period=master
