# Generated by Django 4.2.11 on 2024-12-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marketplace',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
    ]
